### ISSUE TITLE
Support for saving tracking data

### ISSUE THREAD

**Issue by dzhoshkun** [dzhoshkun/wherepy#2]
* [x] PyYAML dependency
   * [x] README
   * [x] `setup.py`
* [x] Each launch should create a session file  `000000-2018-02-17-08-49-13.yml` within root sessions folder => will be addressed part of the application
* [x] `SessionLog` class:
   * [x] `SessionLog(filepath)`:
   * [x] `append(tool_pose)`:
     1. [x] `tool_pose` => YAML representation
     1. [x] save the pose:

```yaml
wherepy:
  version: git-described
0:
  port1:
    quaternion: "q0 q1 q2 q3"
    coordinates: "x y z"
    error: e
    quality: qu
    timestamp: t0
1:
  port1:
    quaternion: "q0 q1 q2 q3"
    coordinates: "x y z"
    error: e
    quality: qu
    timestamp: t1
[...]
N:
  port1:
    quaternion: "q0 q1 q2 q3"
    coordinates: "x y z"
    error: e
    quality: qu
    timestamp: tN
```
