### ISSUE TITLE
Fixed floating-point precision in session logs

### ISSUE THREAD

**Issue by dzhoshkun** [dzhoshkun/wherepy#29]
To fix an ugly look like this:

```yml

1:
  1:
    coordinates: [91.4, 84.2, -269.16]
    error: 0.058800000000000005
    quality: 0.9803999999999999
    quaternion: [0.2569, -0.8323, -0.46440000000000003, -0.15940000000000001]
    timestamp: 1519136567.998299
```
